name: Check

on: push

jobs:
  test-react-deploy:
    name: deploy test react
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build frontend
        run: cd root/react-deploy-test && npm run build
      - name: Copy bundle via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "ai-chat/dist"
          target: "/var/www/"