name: Check

on: push

jobs:
  test-react-deploy:
    name: deploy test react
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: List build directory contents
        run: ls -al ./dist

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem root@5.35.11.224 'rm -rf /root/react-deploy-test/dist/*'
          scp -o StrictHostKeyChecking=no -i key.pem -r ./dist/* root@5.35.11.224:/root/react-deploy-test/dist/